yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow, name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow, name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Заголовок',
        max_length=200,
        help_text='Дайте короткое название задаче'
    )
    slug = models.SlugField(
        verbose_name='Адрес для страницы с задаче',
        unique=True
    )
    description = models.TextField(
        verbose_name='Описание'
    )

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет отноститься пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField()
    create = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ('-create',)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['author', 'user'],
                name='unique_follower')
        ]

    def __str__(self):
        return f"{self.author}, follower:{self.user}"

yatube/posts/forms.py
from django.contrib.auth import get_user_model
from django import forms

from .models import Post, Group, Comment


User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст',
            'group': 'Название группы',
            'image': 'Картинка поста',
        }
        help_texts = {
            'text': 'Напишите пост здесь',
            'group': 'Выберите свою группу',
        }
    text = forms.CharField(widget=forms.Textarea)
    group = forms.ModelChoiceField(Group.objects.all(), required=False)


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }
        help_texts = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
import django

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm


NUMBER_TEN = 10


def get_paginator(posts, request):
    paginator = Paginator(posts, NUMBER_TEN)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'paginator': paginator,
        'page_number': page_number,
        'page_obj': page_obj,
    }


def index(request: django.http.HttpRequest) -> django.http.HttpResponse:
    """Return a HttpResponse whose content is filled with the result of calling
    django.template.loader.render_to_string() with the passed arguments.
    """
    template = 'posts/index.html'
    context = get_paginator(Post.objects.all(), request)
    return render(request, template, context)


def group_posts(request: django.http.HttpRequest,
                slug: str) -> django.http.HttpResponse:
    """Return a HttpResponse whose content is filled with the result of calling
    django.template.loader.render_to_string() with the passed arguments.
    """
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'posts': posts,
    }
    context.update(get_paginator(group.posts.all(), request))
    return render(request, template, context)


def profile(request: django.http.HttpRequest,
            username: str) -> django.http.HttpResponse:
    """This view render profile page by its username."""
    author = get_object_or_404(User, username=username)
    context = {
        'author': author,
    }
    context.update(get_paginator(author.posts.all(), request))
    return render(request, 'posts/profile.html', context)


def post_detail(request: django.http.HttpRequest,
                post_id: int) -> django.http.HttpResponse:
    """This view render profile page by its username."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    count_post = post.author.posts.count()
    comments = post.comments.all()
    context = {
        'author': post.author,
        'post': post,
        'count_post': count_post,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if request.method == "POST":
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author.username)
    context = {
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)
    if post.author != request.user:
        return redirect('post:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {'form': form,
               'post': post,
               'is_edit': True
               }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@cache_page(60 * 15)
def my_view(request):
    return render(request, 'posts/index.html')


@login_required
def follow_index(request):
    """Информация о текущем пользователе доступа."""
    post = Post.objects.filter(Post, author=request.user)
    context = {
        'title': "Посты в подписке",
        'post': post,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора."""
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", author)


@login_required
def profile_unfollow(request, username):
    """Дизлайк,отписка."""
    Follow.objects.filter(
        user=request.user, author__username=username
    ).delete()
    return redirect("posts:profile", username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
    {% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}
{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    {% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}
                </div>
                <div class="card-body">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3 p-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field }}
                                {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                                {% if is_edit %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load cache %}
{% load thumbnail %}
{% block title %} <title>Посты авторов </title>{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <ul>
      <li>
        {% cache 500 sidebar request.user.username %}
          Автор: 
          <a href="{% url 'posts:profile' post.author.username %}">{% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author.username }}{% endif %}</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        {% endcache %} 
      </li>
    </ul>
    <p>{{ post.text|linebreaksbr }}</p>  
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}  
    {% if post.group %}
        <a href="{% url "posts:group_list" post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "includes/paginator.html" %}  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} 
  <title> Записи сообщества </title> {{ group }} 
{% endblock %}
{% block content %}
  <article>
    <h1> {{ group }} </h1>
    <p> {{ group.description|linebreaksbr }} </p>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор:
          <a href="{% url 'posts:profile' post.author.username %}">{% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author.username }}{% endif %}</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
  </article>
{% include 'includes/paginator.html' %}  
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %} <title>Последние обновления на сайт </title>{% endblock %}
{% block content %}
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  {% if post.group %}
      <a href="{% url "posts:group_list" post.group.slug %}"">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include "includes/paginator.html" %}  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
  <title>Пост {{ post.text|truncatechars:30 }}</title>
{% endblock %}
{% block content%}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}  
              <li class="list-group-item">
                Группа: {{ group }}
                <a href="{% url "posts:group_list" post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }} 
                  <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              <p>{{ post.text }}</p>
              <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
          <p>
          </p>
          {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment.text }}
              </p>
            </div>
          </div>
        {% endfor %}
        </article>
      </div> 
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}  <title>Профайл пользователя</title>{{author.get_full_name}} {% endblock %}
{% block content %}
  <div class='mb-5'>  
  {% for post in page_obj %}
  <h1>Все посты пользователя {{ author }} </h1>
  <h3>Всего постов: {{ sum_posts }} </h3>
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
  {% endif %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url "posts:profile" post.author.username %}">все посты пользователя</a>
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|truncatechars:30 }}</p>
        <a href="{% url "posts:post_detail" post.id %}">подробная информация </a>
    </article>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
    {% if post.group %}
      <a href="{% url "posts:group_list" post.group.slug %}">все записи группы</a>
    {% endif %}
  {% endfor %}
  {% include "includes/paginator.html" %}
  </div>
{% endblock %}

yatube/templates/posts/update_post.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Редактировать пост</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <!-- пункты меню видны только авторизованному пользователю -->
            <li class="nav-item">
              <a class="nav-link active" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <!-- конец пункты меню видны только авторизованному пользователю -->
            <!-- пункты меню видны только неавторизованному пользователю -->
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
            <!-- конец пункты меню видны только неавторизованному пользователю -->        
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Сохранить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>